### ISSUE TITLE
上传后一直停止在解析结果中。。。是何原因？具体见图

### ISSUE THREAD

**Issue by drw2005** [jokin1999/SMMS_Uploader#10]
<img src="https://s2.ax1x.com/2020/03/11/8A0gUK.png" alt="8A0gUK.png" border="0" />

**Comment by josark2005** [comment]
可能是smms图床更新了API，软件没有跟进

**Comment by drw2005** [comment]
> 可能是smms图床更新了API，软件没有跟进
希望能抽空更新一下，软件很好用。

**Comment by josark2005** [comment]
已解决，可执行文件不再提供，如需可执行文件（EXE文件）详见[发布页](https://github.com/jokin1999/SMMS_Uploader/releases/tag/1.0.7)自行操作生成EXE文件。

感谢支持

**Comment by drw2005** [comment]
> 已解决，可执行文件不再提供，如需可执行文件（EXE文件）详见[发布页](https://github.com/jokin1999/SMMS_Uploader/releases/tag/1.0.7)自行操作生成EXE文件。
> 
> 感谢支持

谢谢更新，软件很好用。

**Comment by drw2005** [comment]
用了下1.07版本，图片上传怎么感觉比以前的慢了很多，一个很小的图片，等好很久才成功。

**Comment by josark2005** [comment]
这是SMMS图床的接口问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "drw2005"<notifications@github.com&gt;; 
发送时间: 2020年3月30日(星期一) 下午3:26
收件人: "jokin1999/SMMS_Uploader"<SMMS_Uploader@noreply.github.com&gt;; 
抄送: "Joe"<327928971@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [jokin1999/SMMS_Uploader] 上传后一直停止在解析结果中。。。是何原因？具体见图 (#10)





 
用了下1.07版本，图片上传怎么感觉比以前的慢了很多，一个很小的图片，等好很久才成功。
 
&mdash;
